use serde::Serialize;
use spac_core::{
    BoardProfile, Diagnostic, MetadataModel, HLS_CSIM_RUN_SCHEMA_VERSION,
    HLS_TRAITS_RUN_SCHEMA_VERSION, METADATA_SCHEMA_VERSION,
};

pub const GENERATED_HEADER_FILE: &str = "packet.hpp";
pub const GENERATED_CSIM_SMOKE_FILE: &str = "csim_smoke.cpp";
pub const GENERATED_HLS_CONFIG_FILE: &str = "hls_config.cfg";
pub const GENERATED_CSIM_TCL_FILE: &str = "run_csim.tcl";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedHlsTraits {
    pub file_name: String,
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedTextArtifact {
    pub file_name: String,
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedHlsCsimPackage {
    pub artifacts: Vec<GeneratedTextArtifact>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct HlsTraitsGenerationReport {
    pub schema_version: String,
    pub protocol_name: String,
    pub trust_level: String,
    pub header_path: String,
    pub manifest_path: String,
    pub limitations: Vec<String>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct HlsCsimPackageFiles {
    pub packet_header_path: String,
    pub smoke_source_path: String,
    pub hls_config_path: String,
    pub run_tcl_path: String,
    pub log_paths: Vec<String>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct HlsCsimToolReport {
    pub declared_family: String,
    pub declared_version: String,
    pub requested_binary: Option<String>,
    pub exit_code: Option<i32>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct HlsCsimRunReport {
    pub schema_version: String,
    pub protocol_name: String,
    pub board_profile_id: String,
    pub trust_level: String,
    pub status: String,
    pub package_files: HlsCsimPackageFiles,
    pub manifest_path: String,
    pub command: String,
    pub tool: HlsCsimToolReport,
    pub limitations: Vec<String>,
    pub diagnostics: Vec<Diagnostic>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HlsCsimRunReportInput {
    pub status: String,
    pub trust_level: String,
    pub package_files: HlsCsimPackageFiles,
    pub manifest_path: String,
    pub command: String,
    pub tool: HlsCsimToolReport,
    pub diagnostics: Vec<Diagnostic>,
}

pub fn generate_hls_traits(
    metadata: &MetadataModel,
) -> Result<GeneratedHlsTraits, Vec<Diagnostic>> {
    let diagnostics = validate_metadata_for_codegen(metadata);
    if !diagnostics.is_empty() {
        return Err(diagnostics);
    }

    let guard = include_guard(&metadata.protocol_name);
    let routing_key = metadata
        .semantic_bindings
        .get("routing_key")
        .map(String::as_str)
        .unwrap_or("");

    let mut text = String::new();
    push_line(&mut text, "// Generated by SPAC. Do not edit by hand.");
    push_line(
        &mut text,
        "// Evidence trust level: software_model; no HLS csim, synthesis, timing closure, or FPGA measurement was performed.",
    );
    push_line(&mut text, &format!("#ifndef {guard}"));
    push_line(&mut text, &format!("#define {guard}"));
    push_line(&mut text, "");
    push_line(&mut text, "#include <ap_int.h>");
    push_line(&mut text, "#include <cstdint>");
    push_line(&mut text, "");
    push_line(&mut text, "namespace spac_generated {");
    push_line(&mut text, "");
    push_line(
        &mut text,
        &format!(
            "inline constexpr const char* PROTOCOL_NAME = {};",
            cpp_string_literal(&metadata.protocol_name)
        ),
    );
    push_line(
        &mut text,
        &format!(
            "inline constexpr std::uint32_t BUS_WIDTH_BITS = {};",
            metadata.bus_width_bits
        ),
    );
    push_line(
        &mut text,
        &format!(
            "inline constexpr std::uint64_t TOTAL_HEADER_BITS = {};",
            metadata.total_header_bits
        ),
    );
    push_line(
        &mut text,
        &format!(
            "inline constexpr std::uint64_t TOTAL_HEADER_BYTES = {};",
            metadata.total_header_bytes
        ),
    );
    push_line(
        &mut text,
        &format!(
            "inline constexpr std::uint32_t FIELD_COUNT = {};",
            metadata.fields.len()
        ),
    );
    push_line(
        &mut text,
        &format!(
            "inline constexpr const char* ROUTING_KEY_FIELD = {};",
            cpp_string_literal(routing_key)
        ),
    );
    push_line(&mut text, "using packet_word_t = ap_uint<BUS_WIDTH_BITS>;");
    push_line(&mut text, "");
    push_line(&mut text, "struct FieldTrait {");
    push_line(&mut text, "  const char* name;");
    push_line(&mut text, "  const char* semantic;");
    push_line(&mut text, "  std::uint64_t bit_offset;");
    push_line(&mut text, "  std::uint32_t bit_width;");
    push_line(&mut text, "  std::uint64_t byte_offset;");
    push_line(&mut text, "  std::uint64_t flit_index;");
    push_line(&mut text, "  bool crosses_flit_boundary;");
    push_line(&mut text, "};");
    push_line(&mut text, "");
    push_line(&mut text, "inline constexpr FieldTrait FIELDS[] = {");
    for field in &metadata.fields {
        let semantic = field.semantic.as_deref().unwrap_or("");
        push_line(
            &mut text,
            &format!(
                "  {{{}, {}, {}, {}, {}, {}, {}}},",
                cpp_string_literal(&field.name),
                cpp_string_literal(semantic),
                field.bit_offset,
                field.bit_width,
                field.byte_offset,
                field.flit_index,
                cpp_bool(field.crosses_flit_boundary)
            ),
        );
    }
    push_line(&mut text, "};");
    push_line(&mut text, "");
    push_line(&mut text, "}  // namespace spac_generated");
    push_line(&mut text, "");
    push_line(&mut text, &format!("#endif  // {guard}"));

    Ok(GeneratedHlsTraits {
        file_name: GENERATED_HEADER_FILE.to_string(),
        text,
    })
}

pub fn generate_hls_csim_package(
    metadata: &MetadataModel,
    board_profile: &BoardProfile,
) -> Result<GeneratedHlsCsimPackage, Vec<Diagnostic>> {
    let diagnostics = validate_metadata_for_codegen(metadata);
    if !diagnostics.is_empty() {
        return Err(diagnostics);
    }

    let header = generate_hls_traits(metadata)?;

    Ok(GeneratedHlsCsimPackage {
        artifacts: vec![
            GeneratedTextArtifact {
                file_name: header.file_name,
                text: header.text,
            },
            GeneratedTextArtifact {
                file_name: GENERATED_CSIM_SMOKE_FILE.to_string(),
                text: generate_csim_smoke_source(metadata),
            },
            GeneratedTextArtifact {
                file_name: GENERATED_HLS_CONFIG_FILE.to_string(),
                text: generate_hls_config(board_profile),
            },
            GeneratedTextArtifact {
                file_name: GENERATED_CSIM_TCL_FILE.to_string(),
                text: generate_csim_tcl(board_profile),
            },
        ],
    })
}

pub fn hls_traits_generation_report(
    metadata: &MetadataModel,
    header_path: String,
    manifest_path: String,
) -> HlsTraitsGenerationReport {
    HlsTraitsGenerationReport {
        schema_version: HLS_TRAITS_RUN_SCHEMA_VERSION.to_string(),
        protocol_name: metadata.protocol_name.clone(),
        trust_level: "software_model".to_string(),
        header_path,
        manifest_path,
        limitations: vec![
            "Generated HLS traits are derived from metadata only".to_string(),
            "No HLS csim was executed".to_string(),
            "No synthesis, timing closure, or FPGA measurement was performed".to_string(),
        ],
    }
}

pub fn hls_csim_run_report(
    metadata: &MetadataModel,
    board_profile: &BoardProfile,
    input: HlsCsimRunReportInput,
) -> HlsCsimRunReport {
    let status = input.status;
    let trust_level = input.trust_level;
    let mut limitations = vec![
        "Generated HLS csim package validates only the generated metadata/header surface"
            .to_string(),
        "No synthesis, timing closure, post-synthesis report, or FPGA measurement was performed"
            .to_string(),
    ];

    if trust_level != "hls_csim" {
        limitations.push(
            "No successful HLS csim execution evidence is attached to this report".to_string(),
        );
    }
    if status == "blocked" {
        limitations.push(
            "The package is ready for external HLS csim, but local EDA tool execution is blocked"
                .to_string(),
        );
    }

    HlsCsimRunReport {
        schema_version: HLS_CSIM_RUN_SCHEMA_VERSION.to_string(),
        protocol_name: metadata.protocol_name.clone(),
        board_profile_id: board_profile.board_id.clone(),
        trust_level,
        status,
        package_files: input.package_files,
        manifest_path: input.manifest_path,
        command: input.command,
        tool: input.tool,
        limitations,
        diagnostics: input.diagnostics,
    }
}

pub fn validate_metadata_for_codegen(metadata: &MetadataModel) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();

    if metadata.schema_version != METADATA_SCHEMA_VERSION {
        diagnostics.push(Diagnostic::error(
            "SPAC_METADATA_SCHEMA_VERSION",
            "$.schema_version",
            format!(
                "unsupported metadata schema version '{}'; expected '{}'",
                metadata.schema_version, METADATA_SCHEMA_VERSION
            ),
        ));
    }
    if metadata.protocol_name.trim().is_empty() {
        diagnostics.push(Diagnostic::error(
            "SPAC_METADATA_PROTOCOL_NAME_EMPTY",
            "$.protocol_name",
            "metadata protocol name must not be empty",
        ));
    }
    if metadata.bus_width_bits == 0 || !metadata.bus_width_bits.is_power_of_two() {
        diagnostics.push(Diagnostic::error(
            "SPAC_METADATA_BUS_WIDTH",
            "$.bus_width_bits",
            "metadata bus width must be a positive power of two",
        ));
    }
    if metadata.fields.is_empty() {
        diagnostics.push(Diagnostic::error(
            "SPAC_METADATA_FIELDS_EMPTY",
            "$.fields",
            "metadata must contain at least one field",
        ));
    }
    if !metadata.semantic_bindings.contains_key("routing_key") {
        diagnostics.push(Diagnostic::error(
            "SPAC_METADATA_ROUTING_KEY_MISSING",
            "$.semantic_bindings.routing_key",
            "metadata must bind routing_key before HLS trait generation",
        ));
    }

    diagnostics
}

fn generate_csim_smoke_source(metadata: &MetadataModel) -> String {
    let mut text = String::new();
    push_line(&mut text, "// Generated by SPAC. Do not edit by hand.");
    push_line(
        &mut text,
        "// HLS csim smoke harness only; no synthesis, timing closure, or FPGA measurement is implied.",
    );
    push_line(&mut text, "#include \"packet.hpp\"");
    push_line(&mut text, "#include <cstdint>");
    push_line(&mut text, "");
    push_line(
        &mut text,
        &format!(
            "static_assert(spac_generated::BUS_WIDTH_BITS == {}, \"bus width mismatch\");",
            metadata.bus_width_bits
        ),
    );
    push_line(
        &mut text,
        &format!(
            "static_assert(spac_generated::TOTAL_HEADER_BITS == {}, \"header bit width mismatch\");",
            metadata.total_header_bits
        ),
    );
    push_line(
        &mut text,
        &format!(
            "static_assert(spac_generated::FIELD_COUNT == {}, \"field count mismatch\");",
            metadata.fields.len()
        ),
    );
    for (index, field) in metadata.fields.iter().enumerate() {
        push_line(
            &mut text,
            &format!(
                "static_assert(spac_generated::FIELDS[{index}].bit_offset == {}, \"field {index} offset mismatch\");",
                field.bit_offset
            ),
        );
        push_line(
            &mut text,
            &format!(
                "static_assert(spac_generated::FIELDS[{index}].bit_width == {}, \"field {index} width mismatch\");",
                field.bit_width
            ),
        );
    }
    push_line(&mut text, "");
    push_line(
        &mut text,
        "extern \"C\" void spac_csim_smoke(spac_generated::packet_word_t* word_out) {",
    );
    push_line(&mut text, "#pragma HLS INTERFACE ap_none port=word_out");
    push_line(&mut text, "  *word_out = 0;");
    push_line(&mut text, "}");
    push_line(&mut text, "");
    push_line(&mut text, "int main() {");
    push_line(&mut text, "  spac_generated::packet_word_t word = 0;");
    push_line(&mut text, "  spac_csim_smoke(&word);");
    push_line(
        &mut text,
        "  return spac_generated::FIELD_COUNT == 0 ? 1 : 0;",
    );
    push_line(&mut text, "}");
    text
}

fn generate_hls_config(board_profile: &BoardProfile) -> String {
    let mut text = String::new();
    push_line(
        &mut text,
        "# Generated by SPAC. Do not edit by hand; regenerate from metadata and board profile.",
    );
    push_line(&mut text, &format!("part={}", board_profile.fpga_part));
    push_line(&mut text, "");
    push_line(&mut text, "[hls]");
    push_line(&mut text, "flow_target=vivado");
    push_line(&mut text, "package.output.format=ip_catalog");
    push_line(&mut text, "package.output.syn=false");
    push_line(&mut text, "syn.top=spac_csim_smoke");
    push_line(&mut text, &format!("syn.file={GENERATED_CSIM_SMOKE_FILE}"));
    push_line(&mut text, "syn.cflags=-I.");
    push_line(&mut text, "syn.csimflags=-I.");
    push_line(
        &mut text,
        &format!(
            "clock={}MHz",
            clock_frequency_label(board_profile.target_clock_mhz)
        ),
    );
    text
}

fn generate_csim_tcl(board_profile: &BoardProfile) -> String {
    let period_ns = 1000.0 / board_profile.target_clock_mhz;
    let mut text = String::new();
    push_line(&mut text, "# Generated by SPAC. Do not edit by hand.");
    push_line(&mut text, "open_project spac_csim_smoke");
    push_line(&mut text, "set_top spac_csim_smoke");
    push_line(
        &mut text,
        &format!("add_files {GENERATED_CSIM_SMOKE_FILE} -cflags {{-I.}}"),
    );
    push_line(&mut text, "open_solution solution1 -flow_target vivado");
    push_line(
        &mut text,
        &format!("set_part {{{}}}", board_profile.fpga_part),
    );
    push_line(
        &mut text,
        &format!("create_clock -period {:.3} -name default", period_ns),
    );
    push_line(&mut text, "csim_design");
    push_line(&mut text, "exit");
    text
}

fn push_line(text: &mut String, line: &str) {
    text.push_str(line);
    text.push('\n');
}

fn cpp_string_literal(value: &str) -> String {
    let mut literal = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => literal.push_str("\\\\"),
            '"' => literal.push_str("\\\""),
            '\n' => literal.push_str("\\n"),
            '\r' => literal.push_str("\\r"),
            '\t' => literal.push_str("\\t"),
            other if other.is_ascii_graphic() || other == ' ' => literal.push(other),
            other => literal.push_str(&format!("\\x{:02X}", u32::from(other))),
        }
    }
    literal.push('"');
    literal
}

fn include_guard(protocol_name: &str) -> String {
    let mut guard = String::from("SPAC_GENERATED_PACKET_");
    for ch in protocol_name.chars() {
        if ch.is_ascii_alphanumeric() {
            guard.push(ch.to_ascii_uppercase());
        } else {
            guard.push('_');
        }
    }
    guard.push_str("_HPP");
    guard
}

fn cpp_bool(value: bool) -> &'static str {
    if value {
        "true"
    } else {
        "false"
    }
}

fn clock_frequency_label(mhz: f64) -> String {
    if mhz.fract().abs() < f64::EPSILON {
        format!("{mhz:.0}")
    } else {
        let mut label = format!("{mhz:.3}");
        while label.contains('.') && label.ends_with('0') {
            label.pop();
        }
        if label.ends_with('.') {
            label.pop();
        }
        label
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use spac_core::{FieldLayout, ReportLocations, ToolchainProfile};
    use std::collections::BTreeMap;

    #[test]
    fn generated_header_contains_metadata_traits() {
        let generated = generate_hls_traits(&metadata()).expect("generated traits");

        assert_eq!(generated.file_name, "packet.hpp");
        assert!(generated
            .text
            .contains("using packet_word_t = ap_uint<BUS_WIDTH_BITS>;"));
        assert!(generated
            .text
            .contains("inline constexpr const char* PROTOCOL_NAME = \"hft\";"));
        assert!(generated
            .text
            .contains("inline constexpr const char* ROUTING_KEY_FIELD = \"venue\";"));
        assert!(generated
            .text
            .contains("{\"price\", \"price_ticks\", 41, 32, 5, 0, true},"));
        assert!(generated
            .text
            .contains("Evidence trust level: software_model"));
    }

    #[test]
    fn invalid_metadata_is_rejected() {
        let mut metadata = metadata();
        metadata.semantic_bindings.clear();

        let diagnostics = generate_hls_traits(&metadata).expect_err("missing routing key");

        assert!(diagnostics
            .iter()
            .any(|diagnostic| diagnostic.code == "SPAC_METADATA_ROUTING_KEY_MISSING"));
    }

    #[test]
    fn generated_csim_package_contains_header_smoke_config_and_tcl() {
        let package =
            generate_hls_csim_package(&metadata(), &board_profile()).expect("csim package");
        let names: Vec<&str> = package
            .artifacts
            .iter()
            .map(|artifact| artifact.file_name.as_str())
            .collect();

        assert_eq!(
            names,
            vec![
                "packet.hpp",
                "csim_smoke.cpp",
                "hls_config.cfg",
                "run_csim.tcl"
            ]
        );

        let smoke = package
            .artifacts
            .iter()
            .find(|artifact| artifact.file_name == "csim_smoke.cpp")
            .expect("smoke source");
        assert!(smoke.text.contains("#include \"packet.hpp\""));
        assert!(smoke
            .text
            .contains("static_assert(spac_generated::FIELD_COUNT == 2"));
        assert!(smoke.text.contains("extern \"C\" void spac_csim_smoke"));

        let config = package
            .artifacts
            .iter()
            .find(|artifact| artifact.file_name == "hls_config.cfg")
            .expect("hls config");
        assert!(config.text.contains("part=xcu26-vsva1365-2LV-e"));
        assert!(config.text.contains("clock=350MHz"));

        let tcl = package
            .artifacts
            .iter()
            .find(|artifact| artifact.file_name == "run_csim.tcl")
            .expect("csim tcl");
        assert!(tcl.text.contains("csim_design"));
        assert!(tcl.text.contains("create_clock -period 2.857"));
    }

    fn metadata() -> MetadataModel {
        let mut semantic_bindings = BTreeMap::new();
        semantic_bindings.insert("routing_key".to_string(), "venue".to_string());
        semantic_bindings.insert("price_ticks".to_string(), "price".to_string());

        MetadataModel {
            schema_version: METADATA_SCHEMA_VERSION.to_string(),
            protocol_name: "hft".to_string(),
            bus_width_bits: 64,
            total_header_bits: 73,
            total_header_bytes: 10,
            fields: vec![
                FieldLayout {
                    name: "venue".to_string(),
                    semantic: Some("routing_key".to_string()),
                    bit_offset: 0,
                    bit_width: 8,
                    byte_offset: 0,
                    flit_index: 0,
                    crosses_flit_boundary: false,
                },
                FieldLayout {
                    name: "price".to_string(),
                    semantic: Some("price_ticks".to_string()),
                    bit_offset: 41,
                    bit_width: 32,
                    byte_offset: 5,
                    flit_index: 0,
                    crosses_flit_boundary: true,
                },
            ],
            semantic_bindings,
        }
    }

    fn board_profile() -> BoardProfile {
        BoardProfile {
            schema_version: "spac.board-profile.v0".to_string(),
            board_id: "amd-alveo-u45n".to_string(),
            vendor: "AMD".to_string(),
            board_model: "Alveo U45N".to_string(),
            fpga_part: "xcu26-vsva1365-2LV-e".to_string(),
            toolchain: ToolchainProfile {
                family: "Vitis HLS".to_string(),
                version: "2023.2".to_string(),
            },
            target_clock_mhz: 350.0,
            host_interface: "PCIe".to_string(),
            loopback_topology: "host-fpga-host loopback".to_string(),
            report_locations: ReportLocations {
                synthesis_summary: "reports/post_synthesis.json".to_string(),
                timing_summary: "reports/timing_summary.rpt".to_string(),
            },
        }
    }
}
